apiVersion: v1
kind: Service
metadata:
    name: iudx-cil-api
    labels:
        app: iudx-cil-api
    namespace: iudx-cil-api
spec:
    type: NodePort
    selector:
        app: iudx-cil-api
    ports:
        - name: http
          port: 3030
          targetPort: 3030
          nodePort: 30036
          protocol: TCP
